modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="petrolpark"
version="${file.jarVersion}"
displayName="Petrolpark's Library"
#updateJSONURL=""
displayURL="https://www.modrinth.com/mod/petrolpark"
logoFile="logo.png"
#credits=""
authors="petrolpark"
description='''Common code for petrolpark's Create add-ons.'''

[[dependencies.petrolpark]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.petrolpark]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.petrolpark]]
	modId="create"
	mandatory=true
	versionRange="[0.5.1.h,)"
	ordering="AFTER"
	side="BOTH"

[[dependencies.petrolpark]]
    modId="jei"
    mandatory=false
    versionRange="[15.12.3.55,)"
    ordering="AFTER"
    side="CLIENT"